# Generated by Django 5.0.6 on 2024-05-31 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoldCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_proba', models.IntegerField()),
                ('product_cost', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Gold Cost',
                'ordering': ['product_proba'],
            },
        ),
    ]
