# Generated by Django 5.0.1 on 2024-06-03 02:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_product_options_product_data_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BailTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('data_created', models.DateField()),
                ('data_gone', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BailTicket',
                'verbose_name_plural': 'Bail Tickets',
                'ordering': ['data_created'],
            },
        ),
    ]
