# Generated by Django 5.0.1 on 2024-06-03 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_bailticket_ticket_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bailticket',
            name='ticket_file',
            field=models.FileField(blank=True, upload_to='user_tickets'),
        ),
    ]
